FROM node:20.12.2-alpine3.19 AS test

RUN mkdir -p /TicTacToeThreeFile/test-reports && chmod -R 777 /TicTacToeThreeFile/test-reports

WORKDIR /TicTacToeThreeFile

COPY package*.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "test"]