FROM node:20.12.2-alpine3.19 AS test

RUN mkdir /TicTacToeThreeFile /test-reports

WORKDIR /TicTacToeThreeFile

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

CMD ["npm", "run", "test"]